name: Test

on: [ push ]

jobs:
  rust-test:
    name: Rust Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: rustup update stable && rustup default stable

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --verbose
